GET http://localhost:8081/api/v1/items

###

GET http://localhost:8081/api/v1/items?page=0&size=3&keyword=Italian

###

GET http://localhost:8080/api/v1/items?page=0&size=3&keyword=Italian

###

POST http://localhost:8081/api/v1/items
#accept: */*
Content-Type: application/json

{ "name": "Item name Italian", "description": "Item description", "image": "image address", "price": 123.34, "typeIds": [ 1, 3 ]}

###

POST http://localhost:8081/api/v1/items/learn/1
###
POST http://localhost:8081/api/v1/main/save
###
POST http://localhost:8081/api/v1/main/get/1
###
POST http://localhost:8081/api/v1/main/update/1
###
POST http://localhost:8081/api/v1/main/update/2

###


