version: '2'
services:
    searchengine-postgresql:
        image: postgres:11.1
        volumes:
            - ~/volumes/restaurant/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=restaurant
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
        ports:
            - 5432:5432

#    docker-compose -f src/main/docker/postgresql.yml up
#    docker-compose -f src/main/docker/postgresql.yml up -d